services:
    nginx:
        image: nginx:1.23.3
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

    code:
        restart: on-failure
        env_file:
          - .env
        build:
            context: .
            dockerfile: Dockerfile

    api:
        container_name: api
        extends:
            service: code
        expose:
          - 8080
        command: ["web"]

    migrator:
        container_name: migrator
        restart: no
        env_file:
            - .env
        build:
            context: .
            dockerfile: cli.Dockerfile
        command: ["migrate"]

    db:
        container_name: db
        image: postgres:14.1-alpine
        env_file:
            - .env.pg
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 2s
